name: Unit Test
on:
  push:

jobs:
  coverage:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      # TODO: Unit Test Here!
      # Start Unit Test Section

      # End Unit Test Section
      # Start Coverage Collection Section
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
      # End Coverage Collection Section